version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dog-breed-app
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    env_file:
      - ./src/.env

  db:
    image: mysql:8.0.36
    container_name: dog-breed-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dog_breed
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
